- name: Crate Jenkins Jobs
  hosts: localhost
  connection: local
  vars:
    jobs:
      - roboshop-terraform
      - cart
      - catalogue
      - user
      - shipping
      - payment
      - dispatch
  roles:
    - jenkins-jobs