- name: Single branch Pipeline setup
  ansible.builtin.include_tasks:
    file: sp_job.yml
  loop: "{{sp_jobs}}"

- name: Multi branch Pipeline setup
  ansible.builtin.include_tasks:
    file: mp_job.yml
  loop: "{{mp_jobs}}"